### ISSUE TITLE
How to use R to visualize the `result`? 

### ISSUE THREAD

**Issue by X140Yu** [PaulTaykalo/xcode-time-tracker#1]
I've install the `R` environment, but how can I visualize the `result` file, it there any tutorials yet?

**Comment by PaulTaykalo** [comment]
From here:
https://github.com/PaulTaykalo/xcode-time-tracker/tree/master/visualization/r
`Rscript Timecheck.R`

**Comment by sirnacnud** [comment]
I had to install the R packages `readr`, `anytime`, and `ggplot2` before I could run the script.
